/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pixel.client.GUI;

import pixel.client.GUI.photochooser.ImagePreview;
import pixel.client.GUI.photochooser.ImageFilter;
import java.io.File;
import java.rmi.RemoteException;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import pixel.client.Client;
import pixel.client.utils.Utils;
import pixel.shared.classes.Foto;

/**
 *
 * @author Kasper
 */
public class AddPhotoPanel extends javax.swing.JPanel {

    private JFileChooser fc;
    private DefaultListModel selectedPhotosModel;
    private JPanel panel;
    
    ResourceBundle resBund;

    /**
     * Creates new form AddPhotoPanel
     * @param panel 
     */
    public AddPhotoPanel(JPanel panel) {
        
        this.panel = panel;
        selectedPhotosModel = new DefaultListModel();
        initComponents();

        resBund = ResourceBundle.getBundle("pixel.resources.language.Language", Locale.getDefault());
        updateLanguage();

        File file = new File("%userprofile%");
        fc = new JFileChooser();
        fc.setDialogTitle(resBund.getString("ONEORMORE"));
        fc.setCurrentDirectory(file);
        fc.setApproveButtonText(resBund.getString("SELECT"));
        fc.setFileFilter(new ImageFilter());
        fc.setAcceptAllFileFilterUsed(false);
        fc.setAccessory(new ImagePreview(fc));
        fc.setMultiSelectionEnabled(!(panel instanceof AddProductPanel));
    }
    
    private void updateLanguage() {
        jLabel1.setText(resBund.getString("SELECTEDPHOTOS"));
        selectPhotoButton.setText(resBund.getString("SELECTNEW"));
        backButton.setText(resBund.getString("BACK"));
        addPhotoButton.setText(resBund.getString("UPLOAD"));
        this.setName(resBund.getString("ONEORMORE"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectPhotoButton = new javax.swing.JButton();
        addPhotoButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        selectedPhotos = new javax.swing.JList();
        backButton = new javax.swing.JButton();

        setName("Selecteer foto(s)"); // NOI18N

        selectPhotoButton.setText("Selecteer nieuwe foto(s)");
        selectPhotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPhotoButtonActionPerformed(evt);
            }
        });

        addPhotoButton.setText("Upload geselecteerde foto(s)");
        addPhotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPhotoButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Geselecteerde foto(s):");

        selectedPhotos.setModel(selectedPhotosModel);
        jScrollPane1.setViewportView(selectedPhotos);

        backButton.setText("Terug");
        backButton.setActionCommand("");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(selectPhotoButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addPhotoButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectPhotoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPhotoButton)
                    .addComponent(backButton))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPhotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPhotoButtonActionPerformed
        if (fc.getSelectedFiles().length > 0) {
            Foto[] fotos = new Foto[fc.getSelectedFiles().length];
            for (int i = 0; i < fc.getSelectedFiles().length; i++) {
                Foto foto = new Foto(Utils.getExtension(fc.getSelectedFiles()[i]));
                foto.fotoToByte(fc.getSelectedFiles()[i]);
                fotos[i] = foto;
            }
            try {
                Client.getServerConnection().fotoToevoegen(Client.getClientId(), Client.getLoggedinAccount().getEmail(), fotos, !(panel instanceof HoofdPanel));
            } catch (RemoteException ex) {
                Logger.getLogger(AddPhotoPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            Client.getFrame().loadPanel(panel);

        } else {
            JOptionPane.showMessageDialog(null, resBund.getString("SELECTMINIMUM"));
        }
    }//GEN-LAST:event_addPhotoButtonActionPerformed

    private void selectPhotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPhotoButtonActionPerformed
        int returnValue = fc.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            selectedPhotosModel.removeAllElements();
            for (File file : fc.getSelectedFiles()) {
                selectedPhotosModel.addElement(file.getPath());
            }
        } else {
            // venster gesloten.
        }
    }//GEN-LAST:event_selectPhotoButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Client.getFrame().loadPanel(panel);
    }//GEN-LAST:event_backButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPhotoButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton selectPhotoButton;
    private javax.swing.JList selectedPhotos;
    // End of variables declaration//GEN-END:variables
}
