/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pixel.client.GUI;

import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import pixel.client.Client;
import pixel.shared.classes.Factuur;
import pixel.shared.classes.OrderRegel;
import pixel.shared.enums.PersoonType;

/**
 *
 * @author Remi_Arts
 */
public class BestelGeschiedenisPanel extends javax.swing.JPanel {

    ResourceBundle resBund;
    ArrayList<Factuur> facturen;
    ArrayList<OrderRegel> regels;
    DefaultListModel listmodel = new DefaultListModel();
    DefaultListModel listmodel2 = new DefaultListModel();
    /**
     * Creates new form BestelGeschiedenisPanel
     */
    public BestelGeschiedenisPanel() {
        initComponents();
        PersoonType type = Client.getLoggedinAccount().getType();
        
        if (type == PersoonType.FOTOPRODUCENT){     
            try {
                facturen = Client.getServerConnection().getAlleFacturen();
            } 
            catch (RemoteException ex) {
                Logger.getLogger(BestelGeschiedenisPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            lst_facturen.setModel(listmodel);
            listmodel.clear();
            for (Factuur f : facturen) {
                listmodel.addElement("Factuurnummer: " + f.getFactuurnummer() + "       Datum: " + f.getDatum());
            }
        }
        else if(type == PersoonType.KLANT){                
            try {
                facturen = Client.getServerConnection().getKlantFacturen(Client.getLoggedinAccount().getEmail());
            } 
            catch (RemoteException ex) {
                Logger.getLogger(BestelGeschiedenisPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            lst_facturen.setModel(listmodel);
            listmodel.clear();

            for (Factuur f : facturen) {
                listmodel.addElement("Factuurnummer: " + f.getFactuurnummer() + "       Datum: " + f.getDatum());
            }
        }
        
        resBund = ResourceBundle.getBundle("pixel.resources.language.Language", Locale.getDefault());
        UpdateLanguage();
    }

    private void UpdateLanguage() {
        btn_terug.setText(resBund.getString("BACK"));
        lbl_bestellingen.setText(resBund.getString("ORDERS"));
        lbl_producten.setText(resBund.getString("PRODUCTS"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lst_facturen = new javax.swing.JList();
        btn_terug = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_orderregel = new javax.swing.JList();
        lbl_bestellingen = new javax.swing.JLabel();
        lbl_producten = new javax.swing.JLabel();

        lst_facturen.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_facturenValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lst_facturen);

        btn_terug.setText("Terug");
        btn_terug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_terugActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lst_orderregel);

        lbl_bestellingen.setText("Bestellingen:");

        lbl_producten.setText("Producten:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_bestellingen)
                                .addGap(270, 270, 270))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_producten)
                                .addGap(0, 297, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_terug)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_bestellingen)
                    .addComponent(lbl_producten))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_terug)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_terugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_terugActionPerformed
        // TODO add your handling code here:
        Client.getFrame().loadPanel(new HoofdPanel());
    }//GEN-LAST:event_btn_terugActionPerformed

    private void lst_facturenValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lst_facturenValueChanged
        // TODO add your handling code here:
        refreshOrderRegelList();      
    }//GEN-LAST:event_lst_facturenValueChanged

    private void refreshOrderRegelList() {
        
        
        Factuur f = facturen.get(lst_facturen.getSelectedIndex());
        int factuurnummer = f.getFactuurnummer();
        
        try {
            regels = Client.getServerConnection().getOrderRegels(factuurnummer);
        } catch (RemoteException ex) {
            Logger.getLogger(BestelGeschiedenisPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        lst_orderregel.setModel(listmodel2);
        listmodel2.clear();
        for (OrderRegel r : regels) {
            listmodel2.addElement("regelnummer: " + r.getOrderregelnummer() + " prijs: " + r.getPrijs() + " productnummer: " + r.getProductnummer());
        }
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_terug;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_bestellingen;
    private javax.swing.JLabel lbl_producten;
    private javax.swing.JList lst_facturen;
    private javax.swing.JList lst_orderregel;
    // End of variables declaration//GEN-END:variables
}
