/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pixel.client.GUI;

import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.rmi.RemoteException;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import pixel.client.Client;
import pixel.shared.classes.Foto;
import pixel.shared.enums.EffectType;

/**
 *
 * @author Bas
 */
public class FotoBewerkPanel extends javax.swing.JPanel {

    private Foto foto;
    private PhotoPreviewWindow window;
    private ResourceBundle resBund;

    /**
     * Creates new form FotoBewerkPanel
     */
    public FotoBewerkPanel(Foto foto) {
        initComponents();
        this.foto = foto;
        resBund = ResourceBundle.getBundle("pixel.resources.language.Language", Locale.getDefault());
        UpdateLanguage();

        if (window != null) {
            window.dispose();
        }
        window = new PhotoPreviewWindow(this, foto, EffectType.NORMAAL, true);
        rbtn_geen.doClick();
    }

    private void UpdateLanguage() {
        btn_Vorige.setText(resBund.getString("PREVIOUS"));
        btn_opslaan.setText(resBund.getString("SAVE"));
        lbl_kiesEffect.setText(resBund.getString("CHOOSE_EFFECT"));
        rbtn_geen.setText(resBund.getString("EFFECT_NONE"));
        rbtn_grayscale.setText(resBund.getString("EFFECT_GRAY"));
        rbtn_sepia.setText(resBund.getString("EFFECT_SEPIA"));
        btn_Reset.setText(resBund.getString("RESET"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbtn_grayscale = new javax.swing.JRadioButton();
        rbtn_sepia = new javax.swing.JRadioButton();
        btn_opslaan = new javax.swing.JButton();
        btn_Vorige = new javax.swing.JButton();
        lbl_kiesEffect = new javax.swing.JLabel();
        rbtn_geen = new javax.swing.JRadioButton();
        btn_Reset = new javax.swing.JButton();

        buttonGroup1.add(rbtn_grayscale);
        rbtn_grayscale.setText("Grayscale");
        rbtn_grayscale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_grayscaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtn_sepia);
        rbtn_sepia.setText("Sepia");
        rbtn_sepia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_sepiaActionPerformed(evt);
            }
        });

        btn_opslaan.setText("Opslaan");
        btn_opslaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_opslaanActionPerformed(evt);
            }
        });

        btn_Vorige.setText("Vorige");
        btn_Vorige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VorigeActionPerformed(evt);
            }
        });

        lbl_kiesEffect.setText("Klik op een effect om het toe te passen");

        buttonGroup1.add(rbtn_geen);
        rbtn_geen.setText("Geen");
        rbtn_geen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_geenActionPerformed(evt);
            }
        });

        btn_Reset.setText("Herstellen");
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_kiesEffect)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Vorige, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Reset))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtn_geen)
                                .addGap(38, 38, 38)
                                .addComponent(rbtn_sepia)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtn_grayscale)
                                .addGap(0, 8, Short.MAX_VALUE))
                            .addComponent(btn_opslaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_kiesEffect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_geen)
                    .addComponent(rbtn_sepia)
                    .addComponent(rbtn_grayscale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Vorige)
                    .addComponent(btn_opslaan)
                    .addComponent(btn_Reset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_opslaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_opslaanActionPerformed
        try {
            Rectangle crop = window.getPanel().getCrop();
            if (Client.getServerConnection().bewerkteFotoKoppelen(Client.getLoggedinAccount().getEmail(), foto.getFotoNummer(), window.getPanel().getEffect(), (int)crop.getMinX(), (int)crop.getMinY(), (int)crop.getMaxX(), (int)crop.getMaxY())); {
                JOptionPane.showMessageDialog(this, resBund.getString("EDITED_SAVED"), resBund.getString("EDITED_SAVED_TITLE"), JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(FotoBewerkPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_opslaanActionPerformed

    private void btn_VorigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VorigeActionPerformed
        if (window != null) {
            window.dispose();
        }
        Client.getFrame().loadPanel(new HoofdPanel());
    }//GEN-LAST:event_btn_VorigeActionPerformed

    private void rbtn_sepiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_sepiaActionPerformed
        if (window != null) {
            window.dispose();
        }
        window = new PhotoPreviewWindow((JPanel) this, foto, EffectType.SEPIA, true);
    }//GEN-LAST:event_rbtn_sepiaActionPerformed

    private void rbtn_grayscaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_grayscaleActionPerformed
        if (window != null) {
            window.dispose();
        }
        window = new PhotoPreviewWindow((JPanel) this, foto, EffectType.ZWARTWIT, true);
    }//GEN-LAST:event_rbtn_grayscaleActionPerformed

    private void rbtn_geenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_geenActionPerformed
        if (window != null) {
            window.dispose();
        }
        window = new PhotoPreviewWindow((JPanel) this, foto, EffectType.NORMAAL, true);
    }//GEN-LAST:event_rbtn_geenActionPerformed

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        if (window != null) {
            window.getPanel().ResetImage();
        }
    }//GEN-LAST:event_btn_ResetActionPerformed

    public BufferedImage getImage() {
        BufferedImage image = new BufferedImage(window.getPanel().getWidth(), window.getPanel().getHeight(), BufferedImage.TYPE_INT_RGB);
        Graphics2D graphics2D = image.createGraphics();
        window.getPanel().paint(graphics2D);
        return image;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_Vorige;
    private javax.swing.JButton btn_opslaan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lbl_kiesEffect;
    private javax.swing.JRadioButton rbtn_geen;
    private javax.swing.JRadioButton rbtn_grayscale;
    private javax.swing.JRadioButton rbtn_sepia;
    // End of variables declaration//GEN-END:variables
}
