/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pixel.client.GUI;

import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import pixel.client.Client;
import pixel.shared.classes.Foto;
import pixel.shared.classes.Product;

/**
 *
 * @author Frank
 */
public class KoppelProductWindow extends javax.swing.JWindow {

    private KoppelProductPanel koppelpanel;
    private JPanel panel;
    private Thread moveThread;

    /**
     * Creates new form PhotoPreviewWindow
     * @param panel 
     * @param foto 
     */
    public KoppelProductWindow(JPanel panel, Foto foto, Product product) {
        this.panel = panel;
        this.koppelpanel = new KoppelProductPanel(product, foto, this);
        this.setLayout(new java.awt.BorderLayout());

        int width = 250;
        int height = Client.getFrame().getHeight();
        
        this.setPreferredSize(new Dimension(width, height));
        this.getContentPane().add(this.koppelpanel);

        this.setVisible(true);
        this.setLocation(Client.getFrame().getLocation().x + Client.getFrame().getWidth(), Client.getFrame().getLocation().y);   
        this.pack();
        this.validate();
        
        this.moveThread = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    while (isVisible()) {
                        Thread.sleep(1);
                        if (getLocation().x != (Client.getFrame().getLocation().x + Client.getFrame().getWidth()) || getLocation().y != Client.getFrame().getLocation().y) {
                            setLocation(Client.getFrame().getLocation().x + Client.getFrame().getWidth(), Client.getFrame().getLocation().y);
                        }
                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(PhotoPreviewWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        this.moveThread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setAlwaysOnTop(true);
        setType(java.awt.Window.Type.POPUP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
