/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pixel.client.GUI;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.border.LineBorder;
import pixel.client.Client;
import pixel.client.Order;
import pixel.client.Winkelwagen;
import pixel.client.drag_resize.ComponentResizer;
import pixel.client.drag_resize.DragHandler;
import pixel.client.drag_resize.ImageHolder;
import pixel.shared.classes.Foto;
import pixel.shared.classes.Product;

/**
 *
 * @author Simon
 */
public class KoppelProductPanel extends javax.swing.JPanel {

    private KoppelProductWindow window;
    private Product product;
    private Foto previewFoto;
    private Image productImage;
    private Image previewImage;
    ResourceBundle resBund;

    /**
     * Creates new form KoppelProductPanel
     * @param product 
     * @param previewFoto 
     */
    public KoppelProductPanel(Product product, Foto previewFoto, KoppelProductWindow window) {
        this.window = window;
        this.product = product;
        this.previewFoto = previewFoto;
        this.setBorder(new LineBorder(Color.black));
        initComponents();

        resBund = ResourceBundle.getBundle("pixel.resources.language.Language", Locale.getDefault());
        UpdateLanguage();

        this.productImage = product.getFoto().getScaledInstance(250, 250, Image.SCALE_FAST);
        this.previewImage = previewFoto.getFoto().getScaledInstance(75, 75, Image.SCALE_FAST);
        ImageHolder holder = new ImageHolder(previewImage);
        DragHandler dh = new DragHandler(this);
        dh.addComponent(holder);
        ComponentResizer resizer = new ComponentResizer();
        resizer.addComponent(holder);
        this.add(holder);
        holder.setSize(75, 75);
        this.repaint();
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(productImage, 0, 0, this);
    }

    private void UpdateLanguage() {
        btn_voltooien.setText(resBund.getString("COMPLETE"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_voltooien = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(250, 280));

        btn_voltooien.setText("voltooien");
        btn_voltooien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltooienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(btn_voltooien)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addComponent(btn_voltooien)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltooienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltooienActionPerformed
        Winkelwagen.addOrder(new Order(previewFoto, product)); 
        if (window != null) {
            window.dispose();
        }
        Client.getFrame().loadPanel(new HoofdPanel());
    }//GEN-LAST:event_btn_voltooienActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_voltooien;
    // End of variables declaration//GEN-END:variables
}