/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import Interfaces.IDatabaseKoppeling;
import Interfaces.IKlant;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Simon
 */
public class LoginForm extends javax.swing.JFrame {
    IDatabaseKoppeling dbk;

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfAccount = new javax.swing.JTextField();
        tfWachtwoord = new javax.swing.JTextField();
        bInloggen = new javax.swing.JButton();
        bRegistreren = new javax.swing.JButton();
        cbBank = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inloggen");
        setPreferredSize(new java.awt.Dimension(321, 220));

        tfAccount.setText("Account");

        tfWachtwoord.setText("Wachtwoord");
        tfWachtwoord.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        bInloggen.setText("Inloggen");
        bInloggen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInloggenActionPerformed(evt);
            }
        });

        bRegistreren.setText("Registreren");
        bRegistreren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrerenActionPerformed(evt);
            }
        });

        cbBank.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rabobank", "ABN-Amro" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfWachtwoord, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfAccount, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbBank, javax.swing.GroupLayout.Alignment.LEADING, 0, 128, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bRegistreren, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(bInloggen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bInloggen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfWachtwoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRegistreren))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bInloggenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInloggenActionPerformed
        if (!tfAccount.getText().isEmpty() && !tfWachtwoord.getText().isEmpty()) {  
            //poort goed zetten voor de bank
            int poort = 1001;
            if (cbBank.getSelectedIndex() == 0) {
                poort = 1101;
            }
            else if (cbBank.getSelectedIndex() == 1) {
                poort = 1100;
            }
            
            try {
                dbk = (IDatabaseKoppeling)Naming.lookup("rmi://localhost:"+poort+"/DatabaseKoppeling");  
            } catch (NotBoundException | MalformedURLException | RemoteException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                IKlant k = dbk.Login(tfAccount.getText(), tfWachtwoord.getText());
                if (k != null) {       
                    MainForm mf = new MainForm(k, tfAccount.getText(), tfWachtwoord.getText(), dbk);
                    mf.setVisible(true);
                    this.dispose();
                }
                else {
                    JOptionPane.showMessageDialog(null, "Gegevens onjuist");
                }
            } catch (RemoteException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bInloggenActionPerformed

    private void bRegistrerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrerenActionPerformed
        RegistrerenForm rf = new RegistrerenForm();
        rf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bRegistrerenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bInloggen;
    private javax.swing.JButton bRegistreren;
    private javax.swing.JComboBox cbBank;
    private javax.swing.JTextField tfAccount;
    private javax.swing.JTextField tfWachtwoord;
    // End of variables declaration//GEN-END:variables
}
