/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import Interfaces.IDatabaseKoppeling;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Simon
 */
public class RegistrerenForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrerenForm
     */
    IDatabaseKoppeling dbk;
    public RegistrerenForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNaam = new javax.swing.JTextField();
        tfWachtwoord = new javax.swing.JTextField();
        bOk = new javax.swing.JButton();
        cbBank = new javax.swing.JComboBox();
        tfWachtwoord2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfNaam.setText("Naam");
        tfNaam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNaamActionPerformed(evt);
            }
        });

        tfWachtwoord.setText("Wachtwoord");

        bOk.setText("OK");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });

        cbBank.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rabobank", "ABN-Amro" }));

        tfWachtwoord2.setText("Verifieer wachtwoord");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfNaam, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBank, 0, 143, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfWachtwoord2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfWachtwoord, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfWachtwoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bOk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfWachtwoord2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNaamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNaamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNaamActionPerformed

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        if (!tfNaam.getText().isEmpty() && !tfWachtwoord.getText().isEmpty() && !tfWachtwoord2.getText().isEmpty() && tfWachtwoord.getText().equals(tfWachtwoord2.getText())) {
            //poort goed zetten voor de bank
            int poort = 1001;
            if (cbBank.getSelectedIndex() == 0) {
                poort = 1101;
            }
            else if (cbBank.getSelectedIndex() == 1) {
                poort = 1100;
            }
            
            try {
                dbk = (IDatabaseKoppeling)Naming.lookup("rmi://localhost:"+poort+"/DatabaseKoppeling");
                if (dbk.Registreren(tfNaam.getText(), tfWachtwoord.getText())) {
                    JOptionPane.showMessageDialog(null, "Registreren gelukt");
                    new LoginForm().setVisible(true);
                    this.dispose();
                }
                else {
                    JOptionPane.showMessageDialog(null, "Gebruikersnaam bestaal al");
                }
            } catch (    NotBoundException | MalformedURLException | RemoteException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOk;
    private javax.swing.JComboBox cbBank;
    private javax.swing.JTextField tfNaam;
    private javax.swing.JTextField tfWachtwoord;
    private javax.swing.JTextField tfWachtwoord2;
    // End of variables declaration//GEN-END:variables
}
