/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.Iterator;
import stamboom.Gezin;
import stamboom.Persoon;

/**
 *
 * @author Luc
 */
public class BestaandPersoonFrame extends javax.swing.JFrame {
    private Persoon persoon;
    
    /**
     * Creates new form BestaandPersoonFrame
     */
    public BestaandPersoonFrame(Persoon persoon) {
        initComponents();      
        setDefaultCloseOperation(BestaandPersoonFrame.DISPOSE_ON_CLOSE);
        this.persoon = persoon;
        this.UpdateVelden();
    }
    
    private void UpdateVelden()
    {
        persoonPanel.setPersoonsnummer(persoon.getNr());
        persoonPanel.setAchternaam(persoon.getAchternaam());
        persoonPanel.setVoornamen(persoon.getVoornamen());
        persoonPanel.setTussenvoegsel(persoon.getTussenvoegsel());
        persoonPanel.setGeslacht(persoon.getGeslacht());
        persoonPanel.setGebDat(persoon.getGebdat());
        
        cbGezin.removeAllItems();                
        Iterator<Gezin> g = persoon.getGezinnen();
        while (g.hasNext()) {
                cbGezin.addItem(g.next());
            }
            if (cbGezin.getItemCount() == 0) {
                cbGezin.addItem("Geen");
            }
        this.taStamboom.setText(persoon.stamboomGegevensAlsString());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        persoonPanel = new gui.PersoonPanel();
        jLabel1 = new javax.swing.JLabel();
        cbGezin = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        taStamboom = new javax.swing.JTextArea();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Eigen Gezinnen");

        cbGezin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbGezin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGezinActionPerformed(evt);
            }
        });

        taStamboom.setColumns(20);
        taStamboom.setRows(5);
        jScrollPane1.setViewportView(taStamboom);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(persoonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(cbGezin, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(persoonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGezin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbGezinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGezinActionPerformed
        
        if (cbGezin.getSelectedItem() != null && !cbGezin.getSelectedItem().equals("Geen")) {
            Gezin g = (Gezin)cbGezin.getSelectedItem();
            
            
        }
    }//GEN-LAST:event_cbGezinActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbGezin;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private gui.PersoonPanel persoonPanel;
    private javax.swing.JTextArea taStamboom;
    // End of variables declaration//GEN-END:variables
}
