/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.GregorianCalendar;
import java.util.Iterator;
import stamboom.Administratie;
import stamboom.Gezin;
import stamboom.Persoon;
import stamboom.DatabaseKoppeling;
/**
 *
 * @author Luc
 */
public class GezinDialog extends javax.swing.JDialog {

    private Administratie administratie;
    private Gezin gezin;
    DatabaseKoppeling dk = new DatabaseKoppeling();
    
    /**
     * Creates new form GezinDialog
     */
    public GezinDialog(java.awt.Frame parent, boolean modal, Administratie administratie) {
        super(parent, modal);
        this.setModal(true);
        this.administratie = administratie;
        initComponents();
        
        cbOuder1.removeAllItems();
        for (Persoon p : administratie.getPersonen())
        {
            cbOuder1.addItem(p);
        }
        
        cbOuder2.removeAllItems();
        cbOuder2.addItem("geen");
        for (Persoon p : administratie.getPersonen())
        {
            cbOuder2.addItem(p);
        }
        
        lbKinderen.setVisible(false);
        cbKinderen.setVisible(false);
        btnConfirm.setVisible(true);
    }
    
    public GezinDialog(java.awt.Frame parent, boolean modal, Administratie administratie, Gezin gezin) {
        super(parent, modal);
        this.setModal(true);
        this.administratie = administratie;
        initComponents();
        
        cbOuder1.removeAllItems();
        cbOuder1.addItem(gezin.getOuder1());
        
        cbOuder2.removeAllItems();
        if (gezin.getOuder2() != null) {
            cbOuder2.addItem(gezin.getOuder2());
        }
        else {
             cbOuder2.addItem("geen");
        }
        
        cbKinderen.removeAllItems();
        Iterator<Persoon> p = gezin.getKinderen();
        while (p.hasNext()) {
            cbKinderen.addItem(p.next());
        }
        if (cbKinderen.getItemCount() == 0) {
            cbKinderen.addItem("geen");
        }
        
        
        lbKinderen.setVisible(true);
        cbKinderen.setVisible(true);
        btnConfirm.setVisible(false);
    }

    public int getGezinNr(){
        
        return gezin.getNr();
    }
    
    public GregorianCalendar getHuwlijk(){
        return gezin.getHuwelijk();
    }
    
    public GregorianCalendar getScheiding(){
        return gezin.getScheiding();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbOuder1 = new javax.swing.JComboBox();
        cbOuder2 = new javax.swing.JComboBox();
        btnConfirm = new javax.swing.JButton();
        lbKinderen = new javax.swing.JLabel();
        cbKinderen = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ouder1");

        jLabel2.setText("Ouder2");

        cbOuder1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbOuder2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnConfirm.setText("Bevestig");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        lbKinderen.setText("Kinderen");

        cbKinderen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbOuder1, 0, 316, Short.MAX_VALUE)
                            .addComponent(cbOuder2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbKinderen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbKinderen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfirm)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOuder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(cbOuder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbKinderen)
                    .addComponent(cbKinderen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnConfirm)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        Persoon ouder1 = (Persoon) cbOuder1.getSelectedItem();
        Persoon ouder2 = null;
        if (cbOuder2.getSelectedItem() != null && !cbOuder2.getSelectedItem().equals("geen"))
        {
        ouder2 = (Persoon) cbOuder2.getSelectedItem();
        }
        
        administratie.addGezin(ouder1, ouder2);
        dk.addGezin(this.getGezinNr(), ouder1.getNr(), ouder2.getNr(), this.getHuwlijk(), this.getScheiding());
        this.dispose();
    }//GEN-LAST:event_btnConfirmActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox cbKinderen;
    private javax.swing.JComboBox cbOuder1;
    private javax.swing.JComboBox cbOuder2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbKinderen;
    // End of variables declaration//GEN-END:variables
}
