/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Util.Util;
import java.util.GregorianCalendar;
import stamboom.Geslacht;

/**
 *
 * @author Luc
 */
public class PersoonPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersoonPanel
     */
    public PersoonPanel() {
        initComponents();    
    }
    
    public void setAchternaam(String achternaam){
        jtfAchternaam.setText(achternaam);
    }    
   
    public void setPersoonsnummer(int nr) { 
        jtfNummer.setText("" + nr);
    }
        
    public void setVoornamen(String voornamen){
        jtfVoornamen.setText(voornamen);
    }
    
    public void setTussenvoegsel(String tussenvoegsel){
        jtfTussenvoegsel.setText(tussenvoegsel);
    }
    
    public void setGebDat(String datum){
        jtfGeboortedatum.setText(datum);
    }
    
    
    public void setGeslacht(Geslacht g){
        if (g == Geslacht.MAN)
        {
            rbGeslachtM.setSelected(true);
            rbGeslachtV.setSelected(false);
        }
        else
        {
            rbGeslachtM.setSelected(false);
            rbGeslachtV.setSelected(true);
        }
    }

    public int getNr(){
        return Integer.parseInt(jtfNummer.getText());
    }
    
    public Geslacht getGeslacht() {
       if(rbGeslachtM.isSelected())
       {
           return Geslacht.MAN;
       }
       else
       {
           return Geslacht.VROUW;
       }
    }
    
    public String[] getVoornamen() {
        if (!jtfVoornamen.getText().isEmpty()) {
            return jtfVoornamen.getText().trim().split(" ");
        } else {
            return null;
        }
    }
    
    public String getTussenvoegsel(){
        return  jtfTussenvoegsel.getText();
    }

    public String getAchternaam(){
        if (jtfAchternaam.getText().isEmpty()) {
            return null;
        } else {
            return jtfAchternaam.getText();
        }
    }
    
    public GregorianCalendar getGebDat(){
        return Util.datum(this,jtfGeboortedatum.getText());
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbGeslachtM = new javax.swing.JRadioButton();
        rbGeslachtV = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jtfNummer = new javax.swing.JTextField();
        jtfAchternaam = new javax.swing.JTextField();
        jtfVoornamen = new javax.swing.JTextField();
        jtfGeboortedatum = new javax.swing.JTextField();
        jtfTussenvoegsel = new javax.swing.JTextField();

        jLabel1.setText("Persoon");

        jLabel2.setText("Nummer");

        jLabel3.setText("Achternaam");

        jLabel4.setText("Voornamen");

        jLabel5.setText("Tussenvoegsel");

        rbGeslachtM.setText("Mannelijk");
        rbGeslachtM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGeslachtMActionPerformed(evt);
            }
        });

        rbGeslachtV.setText("Vrouwelijk");
        rbGeslachtV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGeslachtVActionPerformed(evt);
            }
        });

        jLabel6.setText("Geboortedatum(dd-mm-jjjj)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rbGeslachtM)
                            .addGap(18, 18, 18)
                            .addComponent(rbGeslachtV)
                            .addGap(201, 201, 201))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfAchternaam, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfVoornamen, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfTussenvoegsel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(31, 31, 31)
                        .addComponent(jtfGeboortedatum, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfAchternaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfVoornamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfTussenvoegsel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbGeslachtM)
                    .addComponent(rbGeslachtV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfGeboortedatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbGeslachtMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGeslachtMActionPerformed
        setGeslacht(Geslacht.MAN);
    }//GEN-LAST:event_rbGeslachtMActionPerformed

    private void rbGeslachtVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGeslachtVActionPerformed
        setGeslacht(Geslacht.VROUW);
    }//GEN-LAST:event_rbGeslachtVActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jtfAchternaam;
    private javax.swing.JTextField jtfGeboortedatum;
    private javax.swing.JTextField jtfNummer;
    private javax.swing.JTextField jtfTussenvoegsel;
    private javax.swing.JTextField jtfVoornamen;
    private javax.swing.JRadioButton rbGeslachtM;
    private javax.swing.JRadioButton rbGeslachtV;
    // End of variables declaration//GEN-END:variables
}
