/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import stamboom.Administratie;
import stamboom.Geslacht;
import stamboom.Gezin;
import stamboom.Persoon;

/**
 *
 * @author Luc
 */
public class StamboomFrame extends javax.swing.JFrame {
    
    Administratie administratie;
    
    
    /**
     * Creates new form StamboomFrame
     */
    public StamboomFrame(Administratie administratie) {
        initComponents();
        setDefaultCloseOperation(StamboomFrame.EXIT_ON_CLOSE);
        this.administratie = administratie;
        this.UpdatePersonen();
    }
    
    private void UpdatePersonen()
    {
        cbPersonen.removeAllItems();
        cbGezinnen.removeAllItems();
        for (Persoon p : administratie.getPersonen()) {
            cbPersonen.addItem(p);
            
            Iterator<Gezin> g = p.getGezinnen();
            while (g.hasNext()) {
                cbGezinnen.addItem(g.next());
            }
        }
        if (cbPersonen.getItemCount() == 0) {
            cbPersonen.addItem("geen");
        }
        if (cbGezinnen.getItemCount() == 0) {
            cbGezinnen.addItem("geen");
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbPersonen = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnBekijkPersoon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbGezinnen = new javax.swing.JComboBox();
        btnBekijkGezin = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miOpslaanAls = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miPersoon = new javax.swing.JMenuItem();
        miGezin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbPersonen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Personen");

        btnBekijkPersoon.setText("Bekijk Gegevens Persoon");
        btnBekijkPersoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBekijkPersoonActionPerformed(evt);
            }
        });

        jLabel2.setText("Gezin");

        cbGezinnen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBekijkGezin.setText("Bekijk Gegevens Gezin");
        btnBekijkGezin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBekijkGezinActionPerformed(evt);
            }
        });

        jMenu1.setLabel("Bestand");

        miOpslaanAls.setText("Opslaan Als");
        miOpslaanAls.setActionCommand("OpslaanAls");
        miOpslaanAls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOpslaanAlsActionPerformed(evt);
            }
        });
        jMenu1.add(miOpslaanAls);

        jMenuBar1.add(jMenu1);

        jMenu2.setActionCommand("Toevoegen");
        jMenu2.setLabel("Toevoegen");

        miPersoon.setText("Persoon");
        miPersoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPersoonActionPerformed(evt);
            }
        });
        jMenu2.add(miPersoon);

        miGezin.setText("Gezin");
        miGezin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGezinActionPerformed(evt);
            }
        });
        jMenu2.add(miGezin);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBekijkPersoon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(btnBekijkGezin, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbGezinnen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cbPersonen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbPersonen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbGezinnen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBekijkPersoon)
                    .addComponent(btnBekijkGezin))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miOpslaanAlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOpslaanAlsActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("."));
        chooser.setFileSelectionMode(JFileChooser.SAVE_DIALOG);
        int result = chooser.showSaveDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) 
        {
            if(chooser.getSelectedFile()!=null)
            {  
                try
                {
                    administratie.save(chooser.getSelectedFile().getAbsolutePath());
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e.toString());
                }
            }    
        }   
    }//GEN-LAST:event_miOpslaanAlsActionPerformed

    private void miPersoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPersoonActionPerformed
       PersoonAanmeldDialog p = new PersoonAanmeldDialog(this, true, administratie);  
       p.setVisible(true);
       UpdatePersonen();
    }//GEN-LAST:event_miPersoonActionPerformed

    private void miGezinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGezinActionPerformed
       GezinDialog g = new GezinDialog(this, true, administratie);  
       g.setVisible(true);
    }//GEN-LAST:event_miGezinActionPerformed

    private void btnBekijkPersoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBekijkPersoonActionPerformed
        if(this.cbPersonen.getSelectedItem() != null && !this.cbPersonen.getSelectedItem().equals("geen")) {
            BestaandPersoonFrame bpf = new BestaandPersoonFrame((Persoon)this.cbPersonen.getSelectedItem());
            bpf.setVisible(true);
        }
    }//GEN-LAST:event_btnBekijkPersoonActionPerformed

    private void btnBekijkGezinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBekijkGezinActionPerformed
        if(this.cbGezinnen.getSelectedItem() != null && !this.cbGezinnen.getSelectedItem().equals("geen")) {
             GezinDialog g = new GezinDialog(this, true, administratie, (Gezin)this.cbGezinnen.getSelectedItem());  
             g.setVisible(true);
        }
    }//GEN-LAST:event_btnBekijkGezinActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBekijkGezin;
    private javax.swing.JButton btnBekijkPersoon;
    private javax.swing.JComboBox cbGezinnen;
    private javax.swing.JComboBox cbPersonen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miGezin;
    private javax.swing.JMenuItem miOpslaanAls;
    private javax.swing.JMenuItem miPersoon;
    // End of variables declaration//GEN-END:variables
}
