
package auctionmanager;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Auction", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Auction {


    /**
     * 
     * @param arg0
     * @return
     *     returns auctionmanager.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItem", targetNamespace = "http://webservice/", className = "auctionmanager.GetItem")
    @ResponseWrapper(localName = "getItemResponse", targetNamespace = "http://webservice/", className = "auctionmanager.GetItemResponse")
    @Action(input = "http://webservice/Auction/getItemRequest", output = "http://webservice/Auction/getItemResponse")
    public Item getItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns auctionmanager.Bid
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newBid", targetNamespace = "http://webservice/", className = "auctionmanager.NewBid")
    @ResponseWrapper(localName = "newBidResponse", targetNamespace = "http://webservice/", className = "auctionmanager.NewBidResponse")
    @Action(input = "http://webservice/Auction/newBidRequest", output = "http://webservice/Auction/newBidResponse")
    public Bid newBid(
        @WebParam(name = "arg0", targetNamespace = "")
        Item arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        User arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Money arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<auctionmanager.Item>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findItemByDescription", targetNamespace = "http://webservice/", className = "auctionmanager.FindItemByDescription")
    @ResponseWrapper(localName = "findItemByDescriptionResponse", targetNamespace = "http://webservice/", className = "auctionmanager.FindItemByDescriptionResponse")
    @Action(input = "http://webservice/Auction/findItemByDescriptionRequest", output = "http://webservice/Auction/findItemByDescriptionResponse")
    public List<Item> findItemByDescription(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "revokeItem", targetNamespace = "http://webservice/", className = "auctionmanager.RevokeItem")
    @ResponseWrapper(localName = "revokeItemResponse", targetNamespace = "http://webservice/", className = "auctionmanager.RevokeItemResponse")
    @Action(input = "http://webservice/Auction/revokeItemRequest", output = "http://webservice/Auction/revokeItemResponse")
    public boolean revokeItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Item arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns auctionmanager.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "offerItem", targetNamespace = "http://webservice/", className = "auctionmanager.OfferItem")
    @ResponseWrapper(localName = "offerItemResponse", targetNamespace = "http://webservice/", className = "auctionmanager.OfferItemResponse")
    @Action(input = "http://webservice/Auction/offerItemRequest", output = "http://webservice/Auction/offerItemResponse")
    public Item offerItem(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Category arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
